import { useState } from 'react'
import ConfiguracaoFormShell from './ConfiguracaoFormShell'
import { carregarLista, idLocal, salvarConfig } from './storage'
type Cat={id:string;nome:string;tipo:'RECEITA'|'DESPESA';ativa:boolean}
const CHAVE='synergias_categorias_financeiras'
const PADRAO:Cat[]=['Venda de Mercadorias','Serviços','Outras Receitas'].map((nome,i)=>({id:`r-${i}`,nome,tipo:'RECEITA',ativa:true})).concat(['Funcionários','Combustível','Aluguel','Impostos','Frete','Marketing','Tarifas Bancárias','Manutenção','Outros'].map((nome,i)=>({id:`d-${i}`,nome,tipo:'DESPESA',ativa:true}))) as Cat[]
export default function CategoriasFinanceiras(){const [lista,setLista]=useState(()=>carregarLista<Cat>(CHAVE,PADRAO));const [nome,setNome]=useState('');const [tipo,setTipo]=useState<'RECEITA'|'DESPESA'>('DESPESA');const [msg,setMsg]=useState('');const persistir=(x:Cat[])=>{setLista(x);salvarConfig(CHAVE,x);setMsg('Categorias financeiras atualizadas.')};const add=()=>{if(!nome.trim())return;persistir([...lista,{id:idLocal('catfin'),nome:nome.trim(),tipo,ativa:true}]);setNome('')};return <ConfiguracaoFormShell category="Configurações • Financeiro" title="Categorias Financeiras" subtitle="Organize receitas e despesas para lançamentos e DRE gerencial." notice={msg||'As categorias padrão foram montadas com base nas despesas e receitas já discutidas para a Synergias.'}>
<section className="config-section"><h3>Nova categoria</h3><div className="config-grid-2"><div className="config-field"><label>Descrição</label><input value={nome} onChange={e=>setNome(e.target.value)}/></div><div className="config-field"><label>Tipo</label><select value={tipo} onChange={e=>setTipo(e.target.value as any)}><option value="RECEITA">Receita</option><option value="DESPESA">Despesa</option></select></div></div><div className="config-inline-actions" style={{marginTop:14}}><button className="config-small-button config-small-button-primary" onClick={add}>Adicionar categoria</button></div></section>
<section className="config-section"><h3>Categorias</h3><div className="config-table-wrap"><table className="config-table"><thead><tr><th>Descrição</th><th>Tipo</th><th>Status</th><th>Ações</th></tr></thead><tbody>{lista.map(c=><tr key={c.id}><td>{c.nome}</td><td>{c.tipo}</td><td><span className={`config-status ${c.ativa?'config-status-ok':'config-status-off'}`}>{c.ativa?'Ativa':'Inativa'}</span></td><td><button className="config-small-button" onClick={()=>persistir(lista.map(x=>x.id===c.id?{...x,ativa:!x.ativa}:x))}>{c.ativa?'Inativar':'Ativar'}</button></td></tr>)}</tbody></table></div></section></ConfiguracaoFormShell>}
