import { useState } from 'react'
import ConfiguracaoFormShell from './ConfiguracaoFormShell'
import { carregarLista, idLocal, salvarConfig } from './storage'
type Forma={id:string;nome:string;tipo:string;instituicao:string;ativo:boolean}
const CHAVE='synergias_formas_pagamento'
const PADRAO:Forma[]=[['BOLETO BANCO INTER','BOLETO','Banco Inter'],['PIX BANCO INTER','PIX','Banco Inter'],['TRANSFERÊNCIA BANCO INTER','TRANSFERÊNCIA','Banco Inter'],['DINHEIRO','DINHEIRO',''],['CARTÃO CRÉDITO SUMUP','CARTÃO','SumUp'],['CARTÃO DÉBITO SUMUP','CARTÃO','SumUp']].map((x,i)=>({id:`padrao-${i}`,nome:x[0],tipo:x[1],instituicao:x[2],ativo:true}))
export default function FormasPagamento(){const [lista,setLista]=useState(()=>carregarLista<Forma>(CHAVE,PADRAO).filter(forma=>!`${forma.nome} ${forma.instituicao}`.toUpperCase().includes('CORA')));const [nome,setNome]=useState('');const [tipo,setTipo]=useState('PIX');const [instituicao,setInstituicao]=useState('');const [msg,setMsg]=useState('');const persistir=(x:Forma[])=>{setLista(x);salvarConfig(CHAVE,x);setMsg('Formas de pagamento salvas.')};const adicionar=()=>{if(!nome.trim())return;if(`${nome} ${instituicao}`.toUpperCase().includes('CORA')){setMsg('Banco Cora não está disponível no sistema.');return}persistir([...lista,{id:idLocal('pag'),nome:nome.trim().toUpperCase(),tipo,instituicao:instituicao.trim(),ativo:true}]);setNome('');setInstituicao('')};return <ConfiguracaoFormShell category="Configurações • Financeiro" title="Formas de Pagamento" subtitle="Centralize as opções disponíveis em orçamento e pedido." notice={msg||'As opções atuais do ERP já foram usadas como cadastro padrão.'}>
<section className="config-section"><h3>Nova forma de pagamento</h3><div className="config-grid"><div className="config-field"><label>Descrição</label><input value={nome} onChange={e=>setNome(e.target.value)}/></div><div className="config-field"><label>Tipo</label><select value={tipo} onChange={e=>setTipo(e.target.value)}><option>BOLETO</option><option>PIX</option><option>TRANSFERÊNCIA</option><option>DINHEIRO</option><option>CARTÃO</option></select></div><div className="config-field"><label>Banco / Instituição</label><input value={instituicao} onChange={e=>setInstituicao(e.target.value)}/></div></div><div className="config-inline-actions" style={{marginTop:14}}><button className="config-small-button config-small-button-primary" onClick={adicionar}>Adicionar forma</button></div></section>
<section className="config-section"><h3>Formas cadastradas</h3><div className="config-table-wrap"><table className="config-table"><thead><tr><th>Descrição</th><th>Tipo</th><th>Instituição</th><th>Status</th><th>Ações</th></tr></thead><tbody>{lista.map(f=><tr key={f.id}><td>{f.nome}</td><td>{f.tipo}</td><td>{f.instituicao||'—'}</td><td><span className={`config-status ${f.ativo?'config-status-ok':'config-status-off'}`}>{f.ativo?'Ativa':'Inativa'}</span></td><td><button className="config-small-button" onClick={()=>persistir(lista.map(x=>x.id===f.id?{...x,ativo:!x.ativo}:x))}>{f.ativo?'Inativar':'Ativar'}</button></td></tr>)}</tbody></table></div></section></ConfiguracaoFormShell>}
