import { useState } from 'react'
import ConfiguracaoFormShell from './ConfiguracaoFormShell'
import { carregarLista, idLocal, salvarConfig } from './storage'
type Nat={id:string;nome:string;tipo:string;cfopDentro:string;cfopFora:string;ativa:boolean}
const CHAVE='synergias_naturezas_operacao'
const PADRAO:Nat[]=['Venda de Mercadoria','Compra para Revenda','Devolução de Venda','Devolução de Compra','Transferência','Remessa','Bonificação'].map((nome,i)=>({id:`nat-${i}`,nome,tipo:nome.includes('Compra')?'ENTRADA':'SAÍDA',cfopDentro:'',cfopFora:'',ativa:true}))
export default function NaturezasOperacao(){const [lista,setLista]=useState(()=>carregarLista<Nat>(CHAVE,PADRAO));const [nome,setNome]=useState('');const [tipo,setTipo]=useState('SAÍDA');const [cfopDentro,setDentro]=useState('');const [cfopFora,setFora]=useState('');const [msg,setMsg]=useState('');const persistir=(x:Nat[])=>{setLista(x);salvarConfig(CHAVE,x);setMsg('Naturezas de operação atualizadas.')};const add=()=>{if(!nome.trim())return;persistir([...lista,{id:idLocal('nat'),nome:nome.trim(),tipo,cfopDentro,cfopFora,ativa:true}]);setNome('');setDentro('');setFora('')};return <ConfiguracaoFormShell category="Configurações • Fiscal" title="Naturezas de Operação" subtitle="Cadastre as operações fiscais usadas pelo ERP." notice={msg||'Os CFOPs não foram preenchidos automaticamente. As regras fiscais devem ser validadas antes do uso em produção.'}>
<section className="config-section"><h3>Nova natureza</h3><div className="config-grid"><div className="config-field"><label>Descrição</label><input value={nome} onChange={e=>setNome(e.target.value)}/></div><div className="config-field"><label>Tipo</label><select value={tipo} onChange={e=>setTipo(e.target.value)}><option>ENTRADA</option><option>SAÍDA</option></select></div><div className="config-field"><label>CFOP dentro do estado</label><input value={cfopDentro} onChange={e=>setDentro(e.target.value)}/></div><div className="config-field"><label>CFOP fora do estado</label><input value={cfopFora} onChange={e=>setFora(e.target.value)}/></div></div><div className="config-inline-actions" style={{marginTop:14}}><button className="config-small-button config-small-button-primary" onClick={add}>Adicionar natureza</button></div></section>
<section className="config-section"><h3>Naturezas cadastradas</h3><div className="config-table-wrap"><table className="config-table"><thead><tr><th>Descrição</th><th>Tipo</th><th>CFOP interno</th><th>CFOP interestadual</th><th>Status</th><th>Ações</th></tr></thead><tbody>{lista.map(n=><tr key={n.id}><td>{n.nome}</td><td>{n.tipo}</td><td>{n.cfopDentro||'Não definido'}</td><td>{n.cfopFora||'Não definido'}</td><td><span className={`config-status ${n.ativa?'config-status-ok':'config-status-off'}`}>{n.ativa?'Ativa':'Inativa'}</span></td><td><button className="config-small-button" onClick={()=>persistir(lista.map(x=>x.id===n.id?{...x,ativa:!x.ativa}:x))}>{n.ativa?'Inativar':'Ativar'}</button></td></tr>)}</tbody></table></div></section></ConfiguracaoFormShell>}
