import { useState } from 'react'
import ConfiguracaoFormShell from './ConfiguracaoFormShell'
import { carregarConfig, salvarConfig } from './storage'
type Config={ambiente:'HOMOLOGACAO'|'PRODUCAO';versao:string;dataAtualizacao:string;ultimoBackup:string}
const CHAVE='synergias_config_sistema'
const PADRAO:Config={ambiente:'HOMOLOGACAO',versao:'0.1.0-homologacao',dataAtualizacao:new Date().toISOString().slice(0,10),ultimoBackup:''}
export default function Sistema(){const [c,setC]=useState(()=>carregarConfig(CHAVE,PADRAO));const [msg,setMsg]=useState('');const salvar=()=>{salvarConfig(CHAVE,c);setMsg('Configurações do sistema salvas.')};const exportar=()=>{const dados:Record<string,string|null>={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('synergias_'))dados[k]=localStorage.getItem(k)};const blob=new Blob([JSON.stringify({exportadoEm:new Date().toISOString(),dados},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`synergias-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);const novo={...c,ultimoBackup:new Date().toISOString()};setC(novo);salvarConfig(CHAVE,novo);setMsg('Backup local exportado.')};return <ConfiguracaoFormShell category="Configurações • Sistema" title="Backup, Ambiente e Versão" subtitle="Identifique o ambiente do ERP e exporte uma cópia dos dados locais." onSave={salvar} notice={msg||(c.ambiente==='HOMOLOGACAO'?'AMBIENTE DE HOMOLOGAÇÃO — NÃO UTILIZAR COMO SISTEMA OFICIAL.':'ATENÇÃO: ambiente marcado localmente como PRODUÇÃO.')}>
<section className="config-section"><h3>Ambiente do sistema</h3><div className="config-grid"><div className="config-field"><label>Ambiente</label><select value={c.ambiente} onChange={e=>setC({...c,ambiente:e.target.value as Config['ambiente']})}><option value="HOMOLOGACAO">Homologação</option><option value="PRODUCAO">Produção</option></select></div><div className="config-field"><label>Versão</label><input value={c.versao} onChange={e=>setC({...c,versao:e.target.value})}/></div><div className="config-field"><label>Data da atualização</label><input type="date" value={c.dataAtualizacao} onChange={e=>setC({...c,dataAtualizacao:e.target.value})}/></div></div></section>
<section className="config-section"><h3>Backup local</h3><p>Exporta para JSON todas as chaves do ERP iniciadas por synergias_ no navegador atual.</p><div className="config-grid-2"><div className="config-field"><label>Último backup exportado</label><input readOnly value={c.ultimoBackup?new Date(c.ultimoBackup).toLocaleString('pt-BR'):'Nenhum backup registrado'}/></div></div><div className="config-inline-actions" style={{marginTop:14}}><button className="config-small-button config-small-button-primary" onClick={exportar}>Exportar backup agora</button><button className="config-small-button" disabled>Restaurar backup — será validado antes da liberação</button></div></section>
</ConfiguracaoFormShell>}
