import { useState } from 'react'
import ConfiguracaoFormShell from './ConfiguracaoFormShell'
import { carregarLista, idLocal, salvarConfig } from './storage'
type Usuario={id:string;nome:string;email:string;perfil:string;ativo:boolean}
const CHAVE='synergias_usuarios'
const PERFIS=['Administrador','Gerente','Vendedor','Financeiro','Estoque']
export default function UsuariosPermissoes(){const [lista,setLista]=useState(()=>carregarLista<Usuario>(CHAVE,[]));const [nome,setNome]=useState('');const [email,setEmail]=useState('');const [perfil,setPerfil]=useState('Administrador');const [msg,setMsg]=useState('');const persistir=(x:Usuario[])=>{setLista(x);salvarConfig(CHAVE,x);setMsg('Usuários atualizados.')};const add=()=>{if(!nome.trim()||!email.trim())return;persistir([...lista,{id:idLocal('usr'),nome:nome.trim(),email:email.trim(),perfil,ativo:true}]);setNome('');setEmail('')};return <ConfiguracaoFormShell category="Configurações • Acesso" title="Usuários e Permissões" subtitle="Prepare os perfis de acesso para o uso online do ERP." notice={msg||'Neste momento o cadastro é local. Login, senha segura e bloqueio real por permissão serão ativados com backend e banco de dados.'}>
<section className="config-section"><h3>Novo usuário</h3><div className="config-grid"><div className="config-field"><label>Nome</label><input value={nome} onChange={e=>setNome(e.target.value)}/></div><div className="config-field"><label>E-mail</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="config-field"><label>Perfil</label><select value={perfil} onChange={e=>setPerfil(e.target.value)}>{PERFIS.map(p=><option key={p}>{p}</option>)}</select></div></div><div className="config-inline-actions" style={{marginTop:14}}><button className="config-small-button config-small-button-primary" onClick={add}>Adicionar usuário</button></div></section>
<section className="config-section"><h3>Usuários</h3>{lista.length===0?<div className="config-empty">Nenhum usuário cadastrado.</div>:<div className="config-table-wrap"><table className="config-table"><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Status</th><th>Ações</th></tr></thead><tbody>{lista.map(u=><tr key={u.id}><td>{u.nome}</td><td>{u.email}</td><td>{u.perfil}</td><td><span className={`config-status ${u.ativo?'config-status-ok':'config-status-off'}`}>{u.ativo?'Ativo':'Inativo'}</span></td><td><button className="config-small-button" onClick={()=>persistir(lista.map(x=>x.id===u.id?{...x,ativo:!x.ativo}:x))}>{u.ativo?'Inativar':'Ativar'}</button></td></tr>)}</tbody></table></div>}</section>
<section className="config-section"><h3>Matriz de permissões</h3><p>Visual inicial dos perfis. A aplicação efetiva depende do sistema de autenticação.</p><div className="config-table-wrap"><table className="config-table"><thead><tr><th>Ação</th><th>Administrador</th><th>Gerente</th><th>Vendedor</th><th>Financeiro</th><th>Estoque</th></tr></thead><tbody>{[['Ver custo','Sim','Sim','Não','Sim','Sim'],['Ver margem','Sim','Sim','Não','Sim','Não'],['Alterar fiscal','Sim','Não','Não','Não','Não'],['Excluir pedido','Sim','Sim','Não','Não','Não'],['Movimentar estoque','Sim','Sim','Não','Não','Sim']].map(r=><tr key={r[0]}>{r.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div></section></ConfiguracaoFormShell>}
