import { useMemo, useState } from 'react'
import { Plus, Save, Trash2 } from 'lucide-react'
import ModuloShell from '../../components/ModuloShell'
import { listarProdutosStorage } from '../../services/produtosStorage'
import '../../styles/novos-modulos.css'

type Marca={id:string;nome:string;ativa:boolean;criadoEm:string}
const KEY='synergias_marcas'
function gerarId(){return typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():`marca-${Date.now()}`}
function ler():Marca[]{try{const d=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(d)?d:[]}catch{return []}}
export default function Marcas(){const produtos=useMemo(()=>listarProdutosStorage(),[]);const [marcas,setMarcas]=useState<Marca[]>(()=>{const atuais=ler();if(atuais.length)return atuais;return Array.from(new Set(produtos.map(p=>String(p.marca||'').trim()).filter(Boolean))).sort().map(nome=>({id:gerarId(),nome,ativa:true,criadoEm:new Date().toISOString()}))});const [nome,setNome]=useState('');function salvar(lista=marcas){localStorage.setItem(KEY,JSON.stringify(lista));setMarcas([...lista]);alert('Marcas salvas com sucesso.')}function adicionar(){const n=nome.trim();if(!n)return alert('Informe o nome da marca.');if(marcas.some(m=>m.nome.toLowerCase()===n.toLowerCase()))return alert('Esta marca já está cadastrada.');const lista=[...marcas,{id:gerarId(),nome:n,ativa:true,criadoEm:new Date().toISOString()}];setNome('');salvar(lista)}return <ModuloShell category="Produtos" title="Marcas" subtitle="Cadastro central de marcas para padronizar produtos, filtros e relatórios." backTo="/produtos" actions={<button className="novo-icon-btn novo-save" onClick={()=>salvar()} title="Salvar"><Save size={25}/></button>}><section className="novo-card"><div className="novo-card-header"><div><h2>Cadastro de marcas</h2><p>Evita duplicidades de grafia e mantém os relatórios consistentes.</p></div></div><div className="novo-inline"><div className="novo-field"><span>Nova marca</span><input value={nome} onChange={e=>setNome(e.target.value)} placeholder="Ex.: Guimarães" onKeyDown={e=>e.key==='Enter'&&adicionar()}/></div><button className="novo-small-btn primary" onClick={adicionar}><Plus size={16}/> Adicionar</button></div></section><section className="novo-card"><div className="novo-table-wrap"><table className="novo-table"><thead><tr><th>Marca</th><th>Status</th><th>Ações</th></tr></thead><tbody>{marcas.map(m=><tr key={m.id}><td><strong>{m.nome}</strong></td><td><button className="novo-small-btn" onClick={()=>setMarcas(at=>at.map(x=>x.id===m.id?{...x,ativa:!x.ativa}:x))}><span className={`novo-badge ${m.ativa?'green':'red'}`}>{m.ativa?'Ativa':'Inativa'}</span></button></td><td><button className="novo-small-btn danger" onClick={()=>confirm(`Excluir a marca ${m.nome}?`)&&setMarcas(at=>at.filter(x=>x.id!==m.id))}><Trash2 size={15}/> Excluir</button></td></tr>)}{!marcas.length&&<tr><td colSpan={3} className="novo-empty">Nenhuma marca cadastrada.</td></tr>}</tbody></table></div></section></ModuloShell>}
