<?php
declare(strict_types=1);
define('SYNERGIAS_AUTH_BOOTSTRAP', true);
require dirname(__DIR__) . '/bootstrap.php';
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
function out(int $s,array $p):never{http_response_code($s);echo json_encode($p,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function txt(mixed $v):string{return trim((string)($v??''));}
function homeDir():string{$h=rtrim((string)(getenv('HOME')?:''),'/\\');if($h!==''&&is_dir($h)&&is_writable($h))return $h;$d=rtrim((string)($_SERVER['DOCUMENT_ROOT']??''),'/\\');if($d!==''){$p=dirname($d);if(is_dir($p)&&is_writable($p))return $p;}throw new RuntimeException('Diretório privado indisponível.');}
function paths():array{$h=homeDir();return ['secret'=>$h.'/.synergias-secrets/fiscal-a1.key','data'=>$h.'/synergias_private/fiscal-a1/certificado.a1.enc.json','dir'=>$h.'/synergias_private/fiscal-nfe','ca'=>__DIR__.'/cacert.pem'];}
function materialA1():array{$p=paths();if(!is_file($p['secret'])||!is_file($p['data']))throw new RuntimeException('Certificado A1 não instalado.');$k=base64_decode(trim((string)file_get_contents($p['secret'])),true);$e=json_decode((string)file_get_contents($p['data']),true);if(!is_string($k)||strlen($k)!==32||!is_array($e))throw new RuntimeException('Armazenamento A1 inválido.');$plain=openssl_decrypt(base64_decode((string)$e['data'],true),'aes-256-gcm',$k,OPENSSL_RAW_DATA,base64_decode((string)$e['iv'],true),base64_decode((string)$e['tag'],true),base64_decode((string)$e['aad'],true));$m=is_string($plain)?json_decode($plain,true):null;if(!is_array($m))throw new RuntimeException('Não foi possível abrir o A1.');$cert=(string)($m['certificatePem']??'');$key=(string)($m['privateKeyPem']??'');if($cert===''||$key===''||!openssl_x509_check_private_key($cert,$key))throw new RuntimeException('Certificado e chave não correspondem.');return ['cert'=>$cert,'key'=>$key,'extras'=>(array)($m['extraCertificates']??[])];}
function tempPem(string $name,string $content):string{$p=paths();if(!is_dir($p['dir'])&&!mkdir($p['dir'],0700,true)&&!is_dir($p['dir']))throw new RuntimeException('Falha ao preparar diretório fiscal.');$f=$p['dir'].'/.'.$name.'-'.bin2hex(random_bytes(8)).'.pem';file_put_contents($f,$content,LOCK_EX);@chmod($f,0600);return $f;}
function transmitir(string $chave,string $amb,array $m):string{$tp=$amb==='PRODUCAO'?'1':'2';$url=$amb==='PRODUCAO'?'https://nfe.sefazrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx':'https://nfe-homologacao.sefazrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx';$xml='<consSitNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00"><tpAmb>'.$tp.'</tpAmb><xServ>CONSULTAR</xServ><chNFe>'.$chave.'</chNFe></consSitNFe>';$body='<?xml version="1.0" encoding="UTF-8"?><soap12:Envelope xmlns:soap12="http://www.w3.org/2003/05/soap-envelope"><soap12:Body><nfeDadosMsg xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4">'.$xml.'</nfeDadosMsg></soap12:Body></soap12:Envelope>';$cert=$m['cert'];foreach($m['extras'] as $x)if(is_string($x)&&trim($x)!=='')$cert.="\n".trim($x)."\n";$cf=tempPem('consulta-cert',$cert);$kf=tempPem('consulta-key',$m['key']);try{$ch=curl_init($url);$opts=[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$body,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>90,CURLOPT_CONNECTTIMEOUT=>25,CURLOPT_SSLCERT=>$cf,CURLOPT_SSLKEY=>$kf,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2,CURLOPT_HTTPHEADER=>['Content-Type: application/soap+xml; charset=utf-8; action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4/nfeConsultaNF"']];$p=paths();if(is_file($p['ca']))$opts[CURLOPT_CAINFO]=$p['ca'];curl_setopt_array($ch,$opts);$r=curl_exec($ch);$err=curl_error($ch);$no=curl_errno($ch);$http=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);if($no!==0||!is_string($r)||$r==='')throw new RuntimeException('Falha na consulta SEFAZ: '.$err.' (cURL '.$no.', HTTP '.$http.').');return $r;}finally{@unlink($cf);@unlink($kf);}}
try{if(strtoupper(txt($_SERVER['REQUEST_METHOD']??''))!=='POST')out(405,['ok'=>false,'mensagem'=>'Método não permitido.']);$u=exigirAutenticacao();if(strcasecmp(txt($u['perfil']??''),'Administrador')!==0)out(403,['ok'=>false,'mensagem'=>'Apenas Administrador.']);$b=json_decode((string)file_get_contents('php://input'),true);$chave=preg_replace('/\D+/','',txt($b['chaveAcesso']??''))?:'';$amb=strtoupper(txt($b['ambiente']??'HOMOLOGACAO'));if(strlen($chave)!==44)throw new RuntimeException('Chave de acesso inválida.');$resp=transmitir($chave,$amb,materialA1());$d=new DOMDocument();if(!@$d->loadXML($resp,LIBXML_NONET))throw new RuntimeException('Resposta SOAP inválida.');$x=new DOMXPath($d);$last=function(string $n)use($x):string{$q=$x->query('//*[local-name()="'.$n.'"]');return $q&&$q->length?trim((string)$q->item($q->length-1)?->textContent):'';};$c=$last('cStat');$mot=$last('xMotivo');$prot=$last('nProt');$dh=$last('dhRecbto');$aut=in_array($c,['100','150'],true);$cancel=in_array($c,['101','151','135','136','155'],true)||str_contains(mb_strtolower($mot),'cancel');out(200,['ok'=>true,'cStat'=>$c,'motivo'=>$mot,'protocolo'=>$prot,'dataRecebimento'=>$dh,'autorizada'=>$aut,'cancelada'=>$cancel,'ambiente'=>$amb,'chaveAcesso'=>$chave]);}catch(Throwable $e){error_log('[NFE CONSULTA V137] '.$e->getMessage());out(500,['ok'=>false,'mensagem'=>$e->getMessage()]);}
